---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: php
      rulesets: Resources/phpmd-rulesets/ruleset.xml
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
  - vendor/*
  - Resources/*
  - view/adminhtml/web/js/elessar/*
